name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Build with Maven
        run: mvn clean package
      
      # NOTIFICAÇÃO DE SUCESSO
      - name: Enviar notificação de sucesso
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject:  Build bem-sucedido - ${{ github.repository }}
          to: lucasqsuzin@gmail.com
          from: GitHub Actions
          body: |
             O build do projeto foi executado com SUCESSO!
            
             Repositório: ${{ github.repository }}
             Branch: ${{ github.ref_name }}
             Commit: ${{ github.sha }}
             Autor: ${{ github.actor }}
             Data: ${{ github.event.head_commit.timestamp }}
            
             Todos os testes passaram!
            
            
      
      # NOTIFICAÇÃO DE FALHA
      - name: Enviar notificação de falha
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject:  Build falhou - ${{ github.repository }}
          to: lucasqsuzin@gmail.com
          from: GitHub Actions
          body: |
             O build do projeto FALHOU!
            
             Repositório: ${{ github.repository }}
             Branch: ${{ github.ref_name }}
             Commit: ${{ github.sha }}
             Autor: ${{ github.actor }}
             Data: ${{ github.event.head_commit.timestamp }}
            
          
